### PR TITLE
1.14.0

### PR DESCRIPTION
**Pull request by andreyz4k**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tswast** [comment]
Thanks for the PR. I'm seeing

```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - google-api-core[version='>=1.6.0'] -> futures[version='>=3.0.0'] -> python[version='>=2.7,<2.8.0a0']
  - python=3.6
```

in the build logs. The `futures` package shouldn't be required for Python 3 as it's a backport. I don't know how to proceed. Probably needs a fix to the `google-api-core-feedstock`?

**Comment by tswast** [comment]
The above issue might be fixed by https://github.com/conda-forge/google-api-core-feedstock/pull/17#pullrequestreview-209308868 which has separate Python 2 and Python 3 packages for google-api-core.

**Comment by tswast** [comment]
@conda-forge-admin please rerender

**Review by tswast — APPROVED** [review]

**Comment by andreyz4k** [comment]
@tswast Can you merge this, please?

**Comment by tswast** [comment]
Thanks for your patience and the contribution @andreyz4k !

**Pull request merged**
